export type ErrorCode =
  | 'MEDIA_NOT_FOUND'
  | 'MEDIA_UNREADABLE'
  | 'UNSUPPORTED_MEDIA'
  | 'NO_PLAYBACK_PATH'
  | 'TRANSCODER_UNAVAILABLE'
  | 'TRANSCODER_FAILED'
  | 'DEVICE_UNSUPPORTED'
  | 'AUTH_REQUIRED'
  | 'PAIRING_REQUIRED'
  | 'NETWORK_ERROR';
