// Builds the README media: a demo library generated by ffmpeg (no copyrighted content), then
// screenshots and a hero GIF captured from the real UI at 1920x1080.
// Usage: node tools/demo.ts        (needs Google Chrome; writes docs/media/*)
import { chromium, type Page } from '@playwright/test';
import { serve } from '@hono/node-server';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { findBins } from '../server/bins.ts';
import { run } from '../server/run.ts';
import { wire } from '../server/wire.ts';
import { buildClient } from './build-client.ts';

const DEMO = resolve('.demo');
const MEDIA = resolve('docs', 'media');
const PORT = 8099;
const BASE = `http://127.0.0.1:${PORT}`;

const H264 = ['-c:v', 'libx264', '-preset', 'fast', '-crf', '23', '-pix_fmt', 'yuv420p', '-g', '48'];
const HEVC = ['-c:v', 'libx265', '-preset', 'fast', '-crf', '26', '-pix_fmt', 'yuv420p', '-x265-params', 'log-level=error'];
const AUDIO = (s: number): string[] => ['-f', 'lavfi', '-i', `sine=frequency=220:sample_rate=48000:duration=${s}`];
const AAC = ['-c:a', 'aac', '-b:a', '128k'];
const SIZE = '1280x720';

const LIBRARY: { file: string; args: string[] }[] = [
  { file: 'Movies/Mandelbrot.Dive.2024.2160p.mkv', args: ['-f', 'lavfi', '-i', `mandelbrot=size=480x270:rate=24:maxiter=256:start_scale=3:end_scale=0.4:end_pts=60,scale=${SIZE}:flags=bicubic`, ...AUDIO(60), '-t', '60', ...HEVC, '-c:a', 'ac3'] },
  { file: 'Movies/Game.of.Life.1970.mp4', args: ['-f', 'lavfi', '-i', `life=size=320x180:rate=12:mold=10:life_color=#ffcc33:death_color=#1f6feb:ratio=0.2,scale=${SIZE}:flags=neighbor`, ...AUDIO(90), '-t', '90', ...H264, ...AAC] },
  { file: 'Movies/Sierpinski.Nights.2021.mkv', args: ['-f', 'lavfi', '-i', `sierpinski=size=${SIZE}:rate=24:type=triangle,hue=h=200`, ...AUDIO(90), '-t', '90', ...H264, ...AAC] },
  { file: 'Movies/Gradient.Drift.2023.mp4', args: ['-f', 'lavfi', '-i', `gradients=size=${SIZE}:rate=24:speed=0.02:seed=7`, ...AUDIO(90), '-t', '90', ...H264, ...AAC] },
  { file: 'Movies/Cellular.2019.mkv', args: ['-f', 'lavfi', '-i', `cellauto=size=320x180:rate=12:rule=30,hue=h=40:s=3,scale=${SIZE}:flags=neighbor`, ...AUDIO(90), '-t', '90', ...H264, ...AAC] },
  { file: 'Movies/Northern.Lights.2022.mp4', args: ['-f', 'lavfi', '-i', `gradients=size=${SIZE}:rate=24:speed=0.03:seed=42:c0=0x0b3d2e:c1=0x2ee6a6:c2=0x6a5acd:nb_colors=3`, ...AUDIO(90), '-t', '90', ...H264, ...AAC] },
  ...[1, 2, 3].map((n) => ({
    file: `Shows/Fractal Planet/Fractal.Planet.S01E0${n}.720p.mkv`,
    args: ['-f', 'lavfi', '-i', `mandelbrot=size=480x270:rate=24:maxiter=256:start_scale=${2.5 - n * 0.5}:end_scale=0.3:end_pts=40,hue=h=${n * 70},scale=${SIZE}:flags=bicubic`, ...AUDIO(40), '-t', '40', ...H264, ...AAC],
  })),
  ...[3, 11, 23, 47, 61, 89].map((seed, i) => ({
    file: `Photos/Holiday ${String(i + 1).padStart(2, '0')}.jpg`,
    args: ['-f', 'lavfi', '-i', `gradients=size=1600x1066:seed=${seed}:nb_colors=4`, '-frames:v', '1', '-q:v', '3'],
  })),
  { file: 'Music/Sine Waves/01 Low Hum.mp3', args: [...AUDIO(30), '-c:a', 'libmp3lame', '-b:a', '128k'] },
];

async function makeLibrary(): Promise<void> {
  const { ffmpeg } = findBins();
  if (!ffmpeg) throw new Error('ffmpeg not found');
  for (const item of LIBRARY) {
    const out = join(DEMO, ...item.file.split('/'));
    if (existsSync(out)) continue;
    mkdirSync(join(out, '..'), { recursive: true });
    const r = await run(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-y', ...item.args, out], 600_000);
    if (r.code !== 0) throw new Error(`${item.file}: ${r.stderr}`);
    process.stdout.write(`made ${item.file}\n`);
  }
}

const ready = (p: Page): Promise<void> => p.locator('.screen[data-ready]').waitFor();
const pause = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

async function capture(): Promise<void> {
  const dataDir = mkdtempSync(join(tmpdir(), 'homecast-demo-'));
  const w = wire({ dataDir, encoder: 'libx264' });
  w.config.update({ port: PORT, roots: [{ id: 'demo', path: DEMO }], mdns: false });
  await w.start();
  await w.scanner.idle();
  const server = serve({ fetch: w.app.fetch, port: PORT, hostname: '127.0.0.1' });
  mkdirSync(MEDIA, { recursive: true });
  const videoDir = mkdtempSync(join(tmpdir(), 'homecast-rec-'));
  const browser = await chromium.launch({ channel: 'chrome' });
  try {
    const ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
    const page = await ctx.newPage();
    // Chrome's own screencast: a JPEG per visual change, with timestamps. No extra ffmpeg download.
    const cdp = await ctx.newCDPSession(page);
    const frames: { file: string; t: number }[] = [];
    cdp.on('Page.screencastFrame', (f: { data: string; sessionId: number; metadata: { timestamp?: number } }) => {
      const file = join(videoDir, `f${String(frames.length).padStart(5, '0')}.jpg`);
      writeFileSync(file, Buffer.from(f.data, 'base64'));
      frames.push({ file, t: f.metadata.timestamp ?? Date.now() / 1000 });
      void cdp.send('Page.screencastFrameAck', { sessionId: f.sessionId }).catch(() => undefined);
    });
    await cdp.send('Page.startScreencast', { format: 'jpeg', quality: 85, maxWidth: 1920, maxHeight: 1080, everyNthFrame: 1 });
    const pin = ((await (await page.request.get(`${BASE}/admin/api/status`)).json()) as { pin: string }).pin;
    await page.goto(BASE);
    await page.locator('.pin').waitFor();
    await page.screenshot({ path: join(MEDIA, 'pair.png') });
    for (const d of pin) {
      await page.keyboard.press(d);
      await pause(120);
    }
    await ready(page);
    // Give two titles some progress so Continue Watching shows on the home screen.
    await page.evaluate(async () => {
      const get = async (p?: string): Promise<{ id: string; title: string; kind: string; meta?: Record<string, unknown> }[]> =>
        (await (await fetch('/api/items' + (p ? '?parent=' + encodeURIComponent(p) : ''))).json()).items;
      const root = (await get()).find((i) => i.meta?.root)!;
      const movies = (await get((await get(root.id)).find((i) => i.title === 'Movies')!.id)).filter((i) => i.kind === 'video');
      const post = (id: string, position: number, duration: number): Promise<Response> =>
        fetch('/api/state/' + id, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ position, duration }) });
      await post(movies.find((m) => m.title.startsWith('Mandelbrot'))!.id, 8, 60);
      await post(movies.find((m) => m.title.startsWith('Northern'))!.id, 35, 90);
    });
    await page.reload();
    await ready(page);
    await pause(1500); // thumbnails fade in
    await page.screenshot({ path: join(MEDIA, 'home.png') });
    for (const k of ['ArrowRight', 'ArrowDown', 'ArrowRight', 'ArrowRight', 'ArrowDown']) {
      await page.keyboard.press(k);
      await pause(450);
    }
    await page.keyboard.press('Enter'); // into the library folder
    await ready(page);
    await pause(600);
    for (const k of ['ArrowRight', 'ArrowRight', 'ArrowLeft']) {
      await page.keyboard.press(k);
      await pause(400);
    }
    // Into Movies, then the HEVC 4K-named title: converted on the fly.
    const movies = page.locator('.tile:has(.title:text-is("Movies"))');
    await movies.hover();
    await pause(300);
    await page.keyboard.press('Enter');
    await ready(page);
    await pause(1200);
    await page.screenshot({ path: join(MEDIA, 'folder.png') });
    await page.locator('.tile:has(.title:text-is("Mandelbrot Dive (2024)"))').hover();
    await pause(500);
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => Number(document.querySelector('.player')?.getAttribute('data-time') ?? 0) > 10, null, { timeout: 30_000 });
    await pause(1500);
    await page.keyboard.press('ArrowRight');
    await pause(2500);
    await page.keyboard.press('Enter'); // pause so the overlay stays for the still
    await pause(400);
    await page.screenshot({ path: join(MEDIA, 'player.png') });
    await page.keyboard.press('Enter');
    await pause(1500);
    await page.keyboard.press('Escape');
    await ready(page);
    await pause(1200);
    await cdp.send('Page.stopScreencast');
    // concat list: each frame shown until the next one arrived
    const lines: string[] = [];
    frames.forEach((f, i) => {
      const next = frames[i + 1]?.t ?? f.t + 1;
      lines.push(`file '${f.file.replace(/\\/g, '/')}'`, `duration ${Math.max(0.02, next - f.t).toFixed(3)}`);
    });
    lines.push(`file '${frames.at(-1)!.file.replace(/\\/g, '/')}'`);
    writeFileSync(join(videoDir, 'frames.txt'), lines.join('\n'));
    await ctx.close();

    const admin = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    await admin.emulateMedia({ colorScheme: 'dark' });
    await admin.goto(`${BASE}/admin`);
    await admin.locator('#qr svg').waitFor();
    await pause(500);
    await admin.screenshot({ path: join(MEDIA, 'admin.png') });

    const { ffmpeg } = findBins();
    const r = await run(
      ffmpeg!,
      ['-hide_banner', '-loglevel', 'error', '-y', '-f', 'concat', '-safe', '0', '-i', join(videoDir, 'frames.txt'), '-vf', 'fps=24,format=yuv420p', '-c:v', 'libx264', '-crf', '20', join(MEDIA, 'demo.webm.mp4')],
      300_000,
    );
    if (r.code !== 0) throw new Error(`stitching frames failed: ${r.stderr}`);
    rmSync(videoDir, { recursive: true, force: true });
  } finally {
    await browser.close();
    server.close();
    w.close();
    rmSync(dataDir, { recursive: true, force: true });
  }
}

/** Hero GIF: 800px wide, 10 fps, 2-pass palette, pairing screen trimmed off the front. */
async function makeGif(): Promise<void> {
  const { ffmpeg } = findBins();
  const src = join(MEDIA, 'demo.webm.mp4');
  const filters = 'fps=10,scale=800:-1:flags=lanczos';
  const pal = join(MEDIA, 'palette.png');
  await run(ffmpeg!, ['-hide_banner', '-loglevel', 'error', '-y', '-ss', '2', '-i', src, '-vf', `${filters},palettegen=max_colors=128:stats_mode=diff`, pal], 300_000);
  const r = await run(
    ffmpeg!,
    ['-hide_banner', '-loglevel', 'error', '-y', '-ss', '2', '-i', src, '-i', pal, '-lavfi', `${filters}[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle`, join(MEDIA, 'demo.gif')],
    300_000,
  );
  if (r.code !== 0) throw new Error(r.stderr);
  rmSync(pal, { force: true });
  await run(ffmpeg!, ['-hide_banner', '-loglevel', 'error', '-y', '-i', src, '-c:v', 'libx264', '-crf', '28', '-pix_fmt', 'yuv420p', '-movflags', '+faststart', '-an', join(MEDIA, 'demo.mp4')], 300_000);
  rmSync(src, { force: true });
  // Photo-like screenshots as 1280-wide JPEGs keep the README fast; UI-only shots stay PNG.
  for (const n of ['home', 'folder', 'player']) {
    await run(ffmpeg!, ['-hide_banner', '-loglevel', 'error', '-y', '-i', join(MEDIA, `${n}.png`), '-vf', 'scale=1280:-1:flags=lanczos', '-q:v', '3', join(MEDIA, `${n}.jpg`)], 60_000);
    rmSync(join(MEDIA, `${n}.png`), { force: true });
  }
}

if (process.argv[1] && import.meta.filename === resolve(process.argv[1])) {
  await buildClient();
  await makeLibrary();
  await capture();
  await makeGif();
  process.stdout.write(`README media written to ${MEDIA}\n`);
}
